# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(228, 716)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_wins_minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_wins_minus.sizePolicy().hasHeightForWidth())
        self.btn_wins_minus.setSizePolicy(sizePolicy)
        self.btn_wins_minus.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.btn_wins_minus.setFont(font)
        self.btn_wins_minus.setObjectName("btn_wins_minus")
        self.horizontalLayout_2.addWidget(self.btn_wins_minus)
        self.btn_wins_plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_wins_plus.sizePolicy().hasHeightForWidth())
        self.btn_wins_plus.setSizePolicy(sizePolicy)
        self.btn_wins_plus.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.btn_wins_plus.setFont(font)
        self.btn_wins_plus.setObjectName("btn_wins_plus")
        self.horizontalLayout_2.addWidget(self.btn_wins_plus)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lbl_wins = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_wins.sizePolicy().hasHeightForWidth())
        self.lbl_wins.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_wins.setFont(font)
        self.lbl_wins.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_wins.setObjectName("lbl_wins")
        self.verticalLayout.addWidget(self.lbl_wins)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_loss_minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_loss_minus.sizePolicy().hasHeightForWidth())
        self.btn_loss_minus.setSizePolicy(sizePolicy)
        self.btn_loss_minus.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.btn_loss_minus.setFont(font)
        self.btn_loss_minus.setObjectName("btn_loss_minus")
        self.horizontalLayout.addWidget(self.btn_loss_minus)
        self.btn_loss_plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_loss_plus.sizePolicy().hasHeightForWidth())
        self.btn_loss_plus.setSizePolicy(sizePolicy)
        self.btn_loss_plus.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.btn_loss_plus.setFont(font)
        self.btn_loss_plus.setObjectName("btn_loss_plus")
        self.horizontalLayout.addWidget(self.btn_loss_plus)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lbl_loss = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_loss.setFont(font)
        self.lbl_loss.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_loss.setObjectName("lbl_loss")
        self.verticalLayout.addWidget(self.lbl_loss)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_excel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_excel.sizePolicy().hasHeightForWidth())
        self.btn_excel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_excel.setFont(font)
        self.btn_excel.setObjectName("btn_excel")
        self.verticalLayout.addWidget(self.btn_excel)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_wins_minus.setText(_translate("MainWindow", "−"))
        self.btn_wins_plus.setText(_translate("MainWindow", "+"))
        self.lbl_wins.setText(_translate("MainWindow", "Wins : 0"))
        self.btn_loss_minus.setText(_translate("MainWindow", "−"))
        self.btn_loss_plus.setText(_translate("MainWindow", "+"))
        self.lbl_loss.setText(_translate("MainWindow", "Losses : 0"))
        self.btn_excel.setText(_translate("MainWindow", "MANDAR AL EXCEL"))

